services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: luminor-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - luminor-net
    env_file:
      - ./src/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 3s
      retries: 5

networks:
  luminor-net:
    driver: bridge