version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: luminor-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - ./src/.env
    networks:
      - shared-net
    depends_on:
      - shared-postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 3s
      retries: 5

networks:
  shared-net:
    external: true