// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameFaq = "faqs"

// Faq mapped from table <faqs>
type Faq struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID        string    `gorm:"column:uuid;default:gen_random_uuid()" json:"uuid"`
	QuestionID  string    `gorm:"column:question_id" json:"question_id"`
	QuestionEn  string    `gorm:"column:question_en" json:"question_en"`
	AnswerID    string    `gorm:"column:answer_id" json:"answer_id"`
	AnswerEn    string    `gorm:"column:answer_en" json:"answer_en"`
	OgImage     string    `gorm:"column:og_image" json:"og_image"`
	IsPublished bool      `gorm:"column:is_published" json:"is_published"`
	CreatedAt   time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Faq's table name
func (*Faq) TableName() string {
	return TableNameFaq
}
