// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID         string    `gorm:"column:uuid;default:gen_random_uuid()" json:"uuid"`
	Slug         string    `gorm:"column:slug;not null" json:"slug"`
	Name         string    `gorm:"column:name;not null" json:"name"`
	Email        string    `gorm:"column:email;not null" json:"email"`
	Photo        string    `gorm:"column:photo" json:"photo"`
	Description  string    `gorm:"column:description" json:"description"`
	Password     string    `gorm:"column:password" json:"password"`
	Role         string    `gorm:"column:role" json:"role"`
	PhoneNumber  string    `gorm:"column:phone_number" json:"phone_number"`
	URLInstagram string    `gorm:"column:url_instagram" json:"url_instagram"`
	URLTiktok    string    `gorm:"column:url_tiktok" json:"url_tiktok"`
	URLFacebook  string    `gorm:"column:url_facebook" json:"url_facebook"`
	URLYoutube   string    `gorm:"column:url_youtube" json:"url_youtube"`
	IsPublished  bool      `gorm:"column:is_published" json:"is_published"`
	CreatedAt    time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
